# -*- coding: utf-8 -*-


#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ToolInterface(object):
    def setupUi(self, ToolInterface):
        ToolInterface.setObjectName("ToolInterface")
        ToolInterface.resize(793, 612)
        self.gridLayout = QtWidgets.QGridLayout(ToolInterface)
        self.gridLayout.setObjectName("gridLayout")
        self.splitter = QtWidgets.QSplitter(ToolInterface)
        self.splitter.setOrientation(QtCore.Qt.Vertical)
        self.splitter.setHandleWidth(8)
        self.splitter.setObjectName("splitter")
        self.stackedWidget = QtWidgets.QStackedWidget(self.splitter)
        self.stackedWidget.setObjectName("stackedWidget")
        self.consoleContainer = QtWidgets.QWidget(self.splitter)
        self.consoleContainer.setObjectName("consoleContainer")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.consoleContainer)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.gridLayout.addWidget(self.splitter, 0, 0, 1, 1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.btnNext = QtWidgets.QPushButton(ToolInterface)
        self.btnNext.setObjectName("btnNext")
        self.horizontalLayout.addWidget(self.btnNext)
        self.btnClose = QtWidgets.QPushButton(ToolInterface)
        self.btnClose.setAutoDefault(False)
        self.btnClose.setObjectName("btnClose")
        self.horizontalLayout.addWidget(self.btnClose)
        self.gridLayout.addLayout(self.horizontalLayout, 2, 0, 1, 1)
        self.progressBar = QtWidgets.QProgressBar(ToolInterface)
        self.progressBar.setProperty("value", 0)
        self.progressBar.setAlignment(QtCore.Qt.AlignCenter)
        self.progressBar.setFormat("")
        self.progressBar.setObjectName("progressBar")
        self.gridLayout.addWidget(self.progressBar, 1, 0, 1, 1)

        self.retranslateUi(ToolInterface)
        self.stackedWidget.setCurrentIndex(-1)
        QtCore.QMetaObject.connectSlotsByName(ToolInterface)

    def retranslateUi(self, ToolInterface):
        _translate = QtCore.QCoreApplication.translate
        ToolInterface.setWindowTitle(_translate("ToolInterface", "Dialog"))
        self.btnNext.setText(_translate("ToolInterface", "Next"))
        self.btnClose.setText(_translate("ToolInterface", "Close"))
